[project]
name = "signal-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=45.0.5",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
